name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, mysql
          coverage: none

      - name: Instalar dependencias (Composer)
        run: composer install --no-dev --optimize-autoloader

      - name: Preparar Laravel
        run: |
          cp .env.example .env || true
          php artisan key:generate || true
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: domains/importexportmustafa.com/public_html/chatarra/
          dangerous-clean-slate: false